### ISSUE TITLE
Delete data older than 1 week

### ISSUE THREAD

**Issue by brson** [Aimeedeer/realtps#4]
The only analysis realtps does requires no more than a week of data. Currently though we store data forever and it doesn't take too many weeks before we run out of disk and the data stops updating.

Add a new "delete" or "gc" job that periodically scans through each chain and deletes old blocks.

The algorithm for doing this should probably be:
- scan backward from the head following all blocks
- push the number of every block older than a week onto a vector
- after scanning all blocks, delete old blocks in reverse order

**Comment by Aimeedeer** [comment]
fixed
