### ISSUE TITLE
Fix solana client

### ISSUE THREAD

**Issue by brson** [Aimeedeer/realtps#44]
The solana code looks deep into the blocks to filter out transacions, [version transactions](https://edge.docs.solana.com/developing/versioned-transactions?utm_medium=email&_hsmi=228967500&utm_content=228967500&utm_source=hs_email) will be activated soon, introducing a new transaction format. It'll probably break things.

**Comment by brson** [comment]
https://blog.quicknode.com/update-to-solana-mainnet/?utm_medium=email&_hsmi=228967500&utm_content=228967500&utm_source=hs_email

https://beta.docs.solana.com/integrations/exchange#versioned-transaction-migration

**Comment by brson** [comment]
Fixing this will likely require an upgrade to our solana deps, and upgrading those is currently blocked because cargo can't resolve the version of zeroize required by curve2559-dalek. dalek has a `<` requirement on zeroize (https://github.com/dalek-cryptography/curve25519-dalek/issues/388).

The only way I know to overcome this is by forking dalek, removing the requirement, and `[patch]`-ing our manifest.

**Comment by Aimeedeer** [comment]
fixed
