### ISSUE TITLE
Reorganize db directory

### ISSUE THREAD

**Issue by brson** [Aimeedeer/realtps#5]
At the moment I frequently have to manually poke in the db directory to debug things. This is tough in the live environment because these directories are huge and listing their contents will tend to freeze a process for a very long time.

Separate the block data from the metadata by putting them into two different directories. This will make looking at the metadata less hazardous.

For each chain make two directories:

- `blocks` - contains all the block files
- `meta` - contains all the other data that is not blocks

**Comment by Aimeedeer** [comment]
fixed
