### ISSUE TITLE
Output per-chain stats after calculation

### ISSUE THREAD

**Issue by brson** [Aimeedeer/realtps#6]
The service is pretty flaky, with chains sometimes falling behind permanently. Monitoring this requires shelling in and looking at logs.

At the end of the calculation job for each chain write some additional info:

- start timestamp of the newest block
- end timestamp of the oldest block
- timestamp when processing started
- timestamp when processing completed

The most important is the start timestamp of the newest block - if it gets too old then we know there's a problem syncing or processing the chain.

Modify realtps_web to dump these stats into an HTML comment so we can look at them with view source.

Modify realtps_web to put a red `(!)` next to any measurements that are severely out of date, with a mouse hover explaining why.

**Comment by Aimeedeer** [comment]
fixed
