### ISSUE TITLE
Hedera Transaction count includes consensus algorithm transactions

### ISSUE THREAD

**Issue by Classic298** [Aimeedeer/realtps#79]
They are massively faking their TPS just like Solana does.

I just watched the explorer live for 5minutes or so. I have only seen like 10 normal transactions or so, the rest was consensus transactions.

There needs to be a warning on the website to not get fooled by Hedera

**Comment by brson** [comment]
I'll give a look this weekend.

**Comment by brson** [comment]
I've given it a look and don't fully understand how HCS is being used, discussed further in https://github.com/Aimeedeer/realtps/issues/78. Continuing in that issue.
